name: Release on pushed tags

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get tag name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Get Tag Message
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo "### ${{ env.TAG }}" >> $GITHUB_STEP_SUMMARY
          git tag -l --format='%(contents)' ${{ env.TAG }} >> $GITHUB_STEP_SUMMARY
          git tag -l --format='%(contents)' ${{ env.TAG }} >> ${{ runner.temp }}/release_body.md

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag Images
        env:
          TAG: ${{ env.TAG }}
          IMAGE: ${{ github.rep}}
        run: |
            docker pull ghcr.io/taranis-ai/taranis-${{ github.event.repository.name }}:latest
            docker buildx imagetools create --tag ghcr.io/taranis-ai/taranis-${{ github.event.repository.name }}:${TAG} --tag ghcr.io/taranis-ai/taranis-${{ github.event.repository.name }}:stable

      - name: Download latest SBOM artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # INSERT COMMAND

      - name: Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          generate_release_notes: true
          append_body: true
          body_path: ${{ runner.temp }}/release_body.md
          files: |
            ${{ runner.temp }}/sbom.json
